name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches: ["dev"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y latexmk texlive-latex-base texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-lang-cyrillic

    - name: Build HTML
      run: |
        make html

    - name: Copy static PDF
      run: |
        mkdir -p build/html/_static
        cp source/_static/project.pdf build/html/_static/project.pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        publish_branch: gh-pages
        force_orphan: true
